# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes 

  tasks:
  - name: Add mongodb key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: EA312927
  
  - name: Add mongodb repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install mongodb package
    apt:
      name: mongodb-org
      update_cache: yes

  - name: Enable and start mongod service
    systemd:
      name: mongod
      enabled: yes
      state: started

