# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes 

  tasks:
  - name: Add mongodb key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: EA312927
  
  - name: Add mongodb repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install mongodb package
    apt:
      name: mongodb-org
      update_cache: yes

  - name: Enable and start mongod service
    systemd:
      name: mongod
      enabled: yes
      state: started

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: all
  gather_facts: no
  become: yes
  vars:
    work_dir: /opt/reddit

  tasks:
  - name: Git clone reddit app
    git:
      repo: https://github.com/Artemmkin/reddit.git
      dest: "{{ work_dir }}"

  - name: Start reddit app - install bundle
    command: bundle install
    args:
      chdir: "{{ work_dir }}"

  - name: copy puma.service file
    copy:
      src: puma.service
      dest: /etc/systemd/system/puma.service

  - name: Start reddit app - start puma
    systemd: 
      name: puma
      enabled: yes
      state: started
